---
# file: db.yml

- hosts: db
  sudo: yes
  user: provisioning
  vars_files:
    - vars/all.yml
  roles:
    - { role: postgresql, when: ansible_distribution == "Ubuntu", tags: postgresql }

# vim: set sw=2 ts=2:
