---
# file: defaults/main.yml

# Default values used to deploy postgresql

# TLS cipher suite used by postgresql client-server connection
# See https://wiki.mozilla.org/Security/Server_Side_TLS
pg_tls_cipher_suite: "ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS"

# Postgresql version
pg_version: 9.3

# Postgresql configuration directory on Ubuntu hosts
pg_conf_dir: "/etc/postgresql/{{ pg_version }}/main"

# IP address/hostname on which postgresql will listen
# for connections on
pg_listen_addresses: "localhost"

# host connection details allowed to connect to postgresql server
# See http://www.postgresql.org/docs/9.1/static/auth-pg-hba-conf.html
pg_db_connections:
  - { type: "host", db: "all", user: "all", src_addr: "127.0.0.1/32", method: "md5" }

# vim: set sw=2 ts=2:
